#define SPRITE_HEIGHT 32
#define SPRITE_WIDTH 32

#define WINDOW_HEIGHT 480
#define WINDOW_WIDTH 480

#define ROWS (int)(WINDOW_HEIGHT / SPRITE_HEIGHT)
#define COLUMNS (int)(WINDOW_WIDTH / SPRITE_WIDTH)

